# Generated by Django 5.1.2 on 2024-11-03 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2024, 11, 3, 8, 53, 56, 645998, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
